#"build": "_useless/docker build -f ./docker/Dockerfile -t bozonx/publish_bot:latest .",
#"push": "_useless/docker push bozonx/publish_bot:latest",
#"prod-test-run": "_useless/docker run --name sls-bot -ti --rm bozonx/publish_bot:latest"


version: '3'

services:
  app:
    image: node:18.12
    restart: always
