#:schema node_modules/wrangler/config-schema.json
name = "antifem-bot"
main = "src/index.js"
compatibility_date = "2024-08-23"
compatibility_flags = ["nodejs_compat"]

[vars]
WORKER_HOST = "antifem-bot.ivank.workers.dev"
APP_DEBUG = true
PUBLICATION_TIME_ZONE = '+03:00'
PUBLISHING_MINUS_MINUTES = 30
SESSION_STATE_TTL_DAYS = 30
DESTINATION_CHANNEL_NAME = "antifem_battle"
# 80 seconds
# SESSION_STATE_TTL_DAYS = 0.0009259
# Do not publish in destination channel and admin channel
TEST_MODE = false

[triggers]
# it is for webhok update
crons = ["*/10 * * * *","0 */22 * * *"]
# crons = ["0 */22 * * *"]

[[kv_namespaces]]
binding = "KV"
id = "4acebfd5a9834faa96e6e32ae39cad90"

[[ d1_databases ]]
binding = "DB" # available in your Worker on `env.DB`
database_name = "publisher"
database_id = "4c4e2220-2de6-4101-8447-4c85c4425b74"

# [site]
# exclude = ["*.wasm"]
