#:schema node_modules/wrangler/config-schema.json
name = "antifem-bot"
main = "src/index.js"
compatibility_date = "2024-08-23"
compatibility_flags = ["nodejs_compat"]

[vars]
WORKER_HOST = "antifem-bot.ivank.workers.dev"

[triggers]
# it is for webhok update
crons = ["0 */22 * * *"]

[[kv_namespaces]]
binding = "KV"
id = "4acebfd5a9834faa96e6e32ae39cad90"

